deb/import.go
The dependency specified when looking for conflicting packages
does not take into account the package version, as by default the
Relation field in the Dependency structure is set to VersionDontCare.
This should fix #185.
=> Update dependency definition in conflicts (fixes #185)

api/publish.go
I implemented `apiPublishUpdateSwitch` for updating repositories through the REST API. This has been working fine for me over several days of relatively heavy testing. Most of this logic is copied verbatim from the command-line `aptly repo update` call. Ideally the common code could be factored out into a standalone update repository function that is used in both places.
I only made this change myself because I needed the ability to update a published (local) repository through the REST API and couldn't wait for it to be implemented. You're welcome to ignore this if you have a better implementation in mind.
This is the first time I have ever written Go, so no promises on the quality. :smile:
=> Implemented apiPublishUpdateSwitch.

deb/publish.go, system/t06_publish/PublishRepo12Test_release, system/t06_publish/PublishRepo15Test_release, system/t06_publish/PublishRepo17Test_release, system/t06_publish/PublishRepo1Test_release, system/t06_publish/PublishSnapshot13Test_release, system/t06_publish/PublishSnapshot15Test_release, system/t06_publish/PublishSnapshot16Test_release, system/t06_publish/PublishSnapshot17Test_release, system/t06_publish/PublishSnapshot1Test_release, system/t06_publish/PublishSnapshot24Test_release, system/t06_publish/PublishSnapshot26Test_release, system/t06_publish/PublishSnapshot2Test_release, system/t06_publish/PublishSnapshot35Test_release, system/t06_publish/PublishSnapshot3Test_release, system/t06_publish/PublishSnapshot4Test_release, system/t06_publish/PublishSwitch1Test_release, system/t06_publish/PublishSwitch8Test_release, system/t06_publish/PublishUpdate1Test_release, system/t06_publish/S3Publish1Test_release, system/t06_publish/S3Publish2Test_release, system/t06_publish/S3Publish3Test_release
Debian's installer validates a mirror by downloading a Release,
and then cross-checking it based on its Codename and Suite.  Without
a Suite field, the installer becomes unhappy (e.g. segfaults) and
won't continue the install.
Making the Codename and Suite the same validates with no problem.
=> d-i requires the Suite field in order to validate a mirror.

deb/deb.go, deb/deb_test.go
Let the user know which deb file is corrupt or badly formatted when throwing an error. No functional change.
=> add diagnostic output

api/api.go
Unlocking the different elements in cache flusher was deferred to the
end of the function. Unfortunately, being a for loop wrapped in a
goroutine, deferred were never executed.
I think that unlocking was still done due to garbage collection.
=> Fix lock handling in cache flusher for API

api/api.go, api/router.go, cmd/api_serve.go, man/aptly.1
After the first API request, the database was locked as long as the API
server is running. This prevents a user to also use the command-line
client. This commit adds a new flag `-no-lock` that will close the
database after each API request.
Closes #234
=> Add a flag to unlock database after each API request

deb/format.go
Otherwise line breaks are not properly handled and the output contains
excess newlines
Fixes #361 
Unfortunately I did not manage to fully comprehend the test suite yet, so I am not able to write a test around this.
=> add Checksums-Sha512 to isMultilineField

files/package_pool.go, files/public.go, http/download.go
Directory creation isn't using the 0777 mode as advertised by the FAQ, this fixes the mode in few places (there might be other places where using 0777 is appropriate).
=> Fixed mkdir mode from 755 to 777

utils/gpg.go
APT 1.2.7, which was released earlier this week and will be in Ubuntu 16.04 LTS, gives a warning on signed repositories where the GPG signature uses SHA-1 or weaker. This will be upgraded to a hard error in Ubuntu 16.10 and in some post-release update to 16.04, as well as in Debian 9. See the [developer's blog post](https://juliank.wordpress.com/2016/03/14/dropping-sha-1-support-in-apt/) and [a follow-up post](https://juliank.wordpress.com/2016/03/15/clarifications-and-updates-on-apt-sha1/) for more information.
This change forces aptly to sign Release and InRelease files with SHA-256. gpg's default signature algorithm is SHA-1, so e.g. http://repo.aptly.info/dists/squeeze/InRelease uses SHA-1. (Users will need to re-publish all existing repositories after this change.)
=> gpg: Sign with SHA-256 for compatibility with APT 1.2.7

cmd/mirror_create.go, deb/remote.go, system/t03_help/MirrorCreateHelpTest_gold, system/t03_help/MirrorCreateTest_gold, system/t03_help/WrongFlagTest_gold, system/t04_mirror/CreateMirror16Test_gold, system/t04_mirror/CreateMirror5Test_gold
Adds a flag -force-architectures to ignore missing architectures from
mirrors. This flag can be used in cases where the mirrored repository
does not provide an "Architecture: " line.
Example Release file:
http://mitaka-jessie.pkgs.mirantis.com/debian/dists/jessie-mitaka-backports/Release
=> Allow overriding architecture info from Release file

system/t04_mirror/CreateMirror11Test_mirror_show, system/t04_mirror/CreateMirror13Test_mirror_show, system/t04_mirror/CreateMirror17Test_mirror_show, system/t04_mirror/CreateMirror1Test_mirror_show, system/t04_mirror/CreateMirror21Test_mirror_show, system/t04_mirror/CreateMirror25Test_mirror_show, system/t04_mirror/CreateMirror2Test_mirror_show, system/t04_mirror/CreateMirror3Test_mirror_show, system/t04_mirror/CreateMirror7Test_mirror_show, system/t04_mirror/EditMirror6Test_mirror_show, system/t04_mirror/ShowMirror1Test_gold, system/t07_serve/__init__.py
- I updated the data in the mirror files so unit tests pass
- Updated api serve exit code in tests to `-2`. As far as I know aptly is still working as intended so I'm not sure if this was changed upstream or if the unit test is actually failing. Let me know if this is incorrect.
=> update unit tests

deb/index_files.go, utils/compress.go, utils/compress_test.go
Creating bzip of contents files is not necessary but might use up the last memory available.
=> only create bzip file if needed. #415

.travis.yml
When developing a feature it often happens during development that I do not want to create a pull request straight away but do some testing in my fork and when successful I will create a PR.
Unfortunately currently travis doesn't run on a fork due to invalid paths. This PR fixes this so a Fork can run the test unit as well.
=> Make Travis CI be able to run on forks

aptly/interfaces.go, cmd/mirror_update.go, deb/remote.go, deb/remote_test.go, http/download.go, http/download_test.go, http/fake.go
When downloading several thousands of packages it sometime occurs that a package runs into a CRC error. With a max tries option it retries a single download and can solve such errors in certain situations where the cause is a network issue.
This fixes issue https://github.com/smira/aptly/issues/149
=> Added --max-tries option to mirror update command

api/repos.go
As those fields are not required, it should be possible to set them to be empty.
=> Allow comment and defaults to be empty when editing a repo through the API

AUTHORS, api/graph.go, system/t12_api/graph.py
When api/graph.{dot,gv} is requested the raw string for dot gets returned.
This allows client-side rendering rather than server-side. It also makes
the optional dependency on graphivz for dot unnecessary to use the graph
endpoint.
=> Allow requesting the unrendered dot graph from the graph endpoint

AUTHORS, cmd/publish.go, cmd/publish_show.go, cmd/snapshot_show.go, man/aptly.1, system/t05_snapshot/CreateSnapshot1Test_snapshot_show, system/t05_snapshot/CreateSnapshot6Test_snapshot_show, system/t05_snapshot/FilterSnapshot1Test_snapshot_show, system/t05_snapshot/FilterSnapshot2Test_snapshot_show, system/t05_snapshot/FilterSnapshot3Test_snapshot_show, system/t05_snapshot/FilterSnapshot7Test_snapshot_show, system/t05_snapshot/MergeSnapshot1Test_snapshot_show, system/t05_snapshot/MergeSnapshot3Test_snapshot_show, system/t05_snapshot/MergeSnapshot6Test_snapshot_show, system/t05_snapshot/MergeSnapshot7Test_snapshot_show, system/t05_snapshot/MergeSnapshot9Test_snapshot_show, system/t05_snapshot/PullSnapshot10Test_snapshot_show, system/t05_snapshot/PullSnapshot11Test_snapshot_show, system/t05_snapshot/PullSnapshot1Test_snapshot_show, system/t05_snapshot/PullSnapshot2Test_snapshot_show, system/t05_snapshot/PullSnapshot3Test_snapshot_show, system/t05_snapshot/PullSnapshot8Test_snapshot_show, system/t05_snapshot/PullSnapshot9Test_snapshot_show, system/t05_snapshot/ShowSnapshot1Test_gold, system/t05_snapshot/ShowSnapshot3Test_gold, system/t06_publish/PublishShow1Test_gold, system/t06_publish/PublishShow2Test_gold, system/t06_publish/__init__.py, system/t06_publish/show.py
For aptly wrapper tools to work such as [pyaptly](https://github.com/adfinis-sygroup/pyaptly) it needs to know sources of a snapshots and published repositories.
Such details are currently part of the description. However such description is hard to parse (or also to read for humans compare aptly publish list) and not always applicable (e.g. when a snapshot has been renamed, merged etc.).
Hence it would be good to have a Sources printed in the snapshot show command and have an additional command publish show to show details of a published repository as well.
Such details may also be very helpful for command line users to get a clue what has been done.
=> Print sources details of snapshots and published repositories

AUTHORS, api/graph.go, cmd/graph.go, deb/graph.go, system/lib.py, system/t12_api/graph.py
[![Build Status](https://travis-ci.org/jola5/aptly.svg?branch=master)](https://travis-ci.org/jola5/aptly)
The default layout of graphviz tends to result in very wide graphs for environments with a lot of repositories. Optionally changing graphviz's rankdir results in a more vertical layout which may be preferable in some cases. In using `layout=horizontal` as default this change is fully backwards compatible. 
I decided to use a generic `layout` switch over a simpler `vertical=false` argument. Maybe someone fancies to implement some of graphviz's more sophisticated layouts like radial. 
`aptly graph`
`aptly graph -layout=horizontal`
`http://localhost:8080/api/graph.png`
`http://localhost:8080/api/graph.png?layout=horizontal`
`aptly graph -layout=vertical` …
=> Support a vertical graph layout in addition to the existing horizontal

Gomfile, deb/deb.go
Fixes #440 
It seems that in the wild there are .deb package which have
`data.tar.gz` which is actually `.tar` archive.
Add magic detection based on signature.
=> Add workaround for reading data.tar.gz as data.tar

.travis.yml, Gomfile, cmd/api_serve.go, cmd/serve.go, system/t07_serve/RootDirInaccessible_gold, system/t07_serve/__init__.py, utils/utils.go
Fixes #467
[![Build Status](https://travis-ci.org/jola5/aptly.svg?branch=master)](https://travis-ci.org/jola5/aptly)
Tests added.
There are only two working options for aptly's rootDir:
1. rootDir does not exist, then we'll create it
2. rootDir exists and is writable
This PR ensures that if no. 2 fails `aptly serve` aborts immediately with a proper error message.
=> Abort serve command if rootDir is inaccessible

database/leveldb.go, database/leveldb_test.go, deb/collections.go, deb/contents.go, deb/publish.go
Attempt to re-implement #454 in a bit different way.
In order to reduce stress on main aptly DB, create temporary levelDB to be used only while generating contents indexes.
Idea and code borrowed shamelessly from #454.
Current implementation might use a lot of memory to store map of paths to packages.
=> Use temporary LevelDB to store contents index

.travis.yml, cmd/api_serve.go, man/aptly.1, system/t12_api/__init__.py, system/t12_api/unix_socket.py
`unix://$PATH` as listen argument will bind aptly to a unix domain socket
rather than TCP.
This allows binding the API to a UDS rather than a port.
Since aptly has no concept of authentication or any amount of high level
API hardening one needs to bottle it up in some other manner. Binding
to a localhost port is often a step in the right direction, ultimately is
still a scary insecure setup as any user on that host getting compromised
would mean that the entire archive is compromised as well.
UDS on the other hand are basically files and have their access managed
by regular file permission. As such, binding to a socket is in fact
the least insecure way to listen as you'd have to explicitly open up the
socket permissions to an access qualified group. In the most conservative
scenario that …
=> support serving the API over unix domain socket

cmd/api_serve.go, man/aptly.1, system/t12_api/__init__.py, system/t12_api/systemd_handover.py, systemd/README.md, systemd/activation/files.go, systemd/activation/listeners.go, systemd/activation/packetconns.go
systemd has a feature called socket activation where initially systemd
manages and listens on ports/uds and only invokes a service when traffic
appears. to then hand over the involved sockets, systemd will pass the
relevant FDs into the invoked process and defines them in the environment.
use coreos/go-systemd to grab the active listeners passed by systemd and
use them to serve the api routes. only one listener may be specified right
now as we also only support one -listen argument for the binary.
this allows admins to craft a systemd socket and service file for aptly
where systemd manages the socket, its permission and its live time, and
lazy start aptly when needed.
Fixes #
=> support systemd activation for `api serve`

cmd/repo_create.go, man/aptly.1, system/t09_repo/CreateRepo7Test_gold, system/t09_repo/CreateRepo7Test_repo_show, system/t09_repo/CreateRepo8Test_gold, system/t09_repo/create.py
Fixes #496
There's no way today to copy snapshot contents to local repo using CLI.
Implement that via simple extension to `aptly repo create` command to accept source snapshot name.
=> Implement new command `aptly repo create ... from snapshot ...`

Gomfile
This seems to fix `NotImplemented` S3 error
=> Bump Go AWS SDK to the latest version

.travis.yml, Makefile, README.rst, aptly/version.go, deb/version_test.go, main.go, system/run.py, system/t01_version/VersionTest_gold, system/t01_version/__init__.py, system/t10_task/RunTask1Test_gold, system/t10_task/run.py, system/t12_api/systemd_handover.py, system/t12_api/unix_socket.py, system/t12_api/version.py
New version format:
* for releases, `x.y.z` (follows tag without leading `v`)
* for nightly builds, `x.y.z+N+hash` (previous version, not the upcoming one)
This means that each nightly build `aptly` would report
correct version now.
Version is now complied into the aptly binary, system tests
automatically check for current version, no need to update them
anymore.
=> Automatic versioning for aptly

aptly/interfaces.go, cmd/package_show.go, deb/import.go, deb/package.go, deb/package_files.go, deb/package_files_test.go, deb/package_test.go, deb/publish_test.go, files/package_pool.go, files/package_pool_test.go, files/public.go, files/public_test.go, s3/public.go, s3/public_test.go, swift/public.go, swift/public_test.go
This is related to #506
As a first step, don't pass MD5 explicitly, pass checksum info object,
so that as a next step we can choose which hash to use.
There should be no functional changes so far.
Next step: stop returning explicit paths from public package pool.
=> Refactoring: use checksums instead of MD5 for pool/published

deb/publish.go
NB: Go `defer` order execution is reverse to the order `defer` statements
are executed.
So before the change, `Drop()` was called before `Close()`, which was no-op.
Change that to explicit order in single func, print errors if they happen.
Fixes #543
=> Fix temporary contents DB being left behind after publishing

.travis.yml
In PR https://github.com/smira/aptly/pull/458 Travis CI was fixed so it runs on forks. Due to the introduction of linters the symlink workaround didn't work properly so a renaming is needed.
=> Making travis CI run again on forks

aptly/interfaces.go, console/progress.go, context/context.go
Fixes #610
`stdout` should be kept clear for output
=> Print error messagge 'unable to open database' to stderr

aptly/interfaces.go, deb/package.go, deb/package_files.go, files/package_pool.go, files/package_pool_test.go, system/t06_publish/PublishSnapshot37Test_gold, system/t06_publish/snapshot.py
While updating mirror, if package file is already in pool path,
field `PoolPath` was left as empty which results in package file
being unavailable later on while publishing.
Fixes #600
This bug was introduced in 1.1.0
=> Fix bug with `PoolPath` field being overwritten on mirror update

AUTHORS, s3/public.go, s3/public_test.go
Original PR: #621
Fixes: #619
I've added unit-test to Martyn's PR.
Without this fix, if `prefix` is set on S3 publish endpoint,
aptly would incorrectly build path cache and re-upload every object
on publish.
=> Fix S3 path caching double-prefix

query/syntax.go, query/syntax_test.go
Fixes: #636
Before this fix, aptly was always treating strings starting with
uppercase letter as field name, which was breaking package queries
like `VMware-Horizon-Client_4.5.0_all`.
Now aptly accepts only fields which don't contain underscore, and
everything else would be parsed as package reference.
=> Allow uppercase package name in package query expressions

cmd/context.go
Skyscrapers wants to contribute back what we use from the community. We are a heavy user of [Concourse](http://concourse.ci/). Concourse supports monitoring changes in different artifacts by way of resource types. We are contributing a new resource type to monitor the release of new versions of a package and trigger builds when that happens:
https://github.com/skyscrapers/apt-package-resource
We are still in development for this resource, but so far I had to make one change to the `aptly` code base to support is in reusing the code: have access to the command context.
This resource type is my first Go contribution which means that also this PR is possibly not the way you should do things in Go. I'm …
=> Expose the context outside of the cmd package.

deb/list.go, system/t04_mirror/SearchMirror4Test_gold, system/t05_snapshot/SearchSnapshot4Test_gold, system/t09_repo/SearchRepo4Test_gold
When searching for packages which might satisfy given dependency,
aptly was first returning packages which `Provides` mentioned
name. By default aptly is picking up only first match (unless
follow all variants options is enabled), so `Provides:` takes
precedence over exact package name match.
Invert this logic by searching first for package name match.
Fixes #618
=> Prefer exact match on package name over provides match

deb/list.go, deb/version.go, deb/version_test.go, system/t05_snapshot/PullSnapshot15Test_gold
When `-dep-follow-all-variants` option is enabled, dependency resolving
process shouldn't stop even if dependency is already satisfied - there
mgiht be other ways to satisfy dependency.
Also fix issue with parsing multiarch specs like
`python:any`.
Fixes #615
=> Fix incomplete dependencies with follow-all-variants

deb/remote.go, linter.json, system/lib.py, utils/config.go
upstream switched the alignment check backend and in doing so fails to run
if the old backend is defined in the config.
also skip alignment linting on a struct we use for byte decoding as we have
no choice in its member order.
Also see https://github.com/alecthomas/gometalinter/commit/90d987842c8b2b8591691f6227d855a3a992e202
Fixes all PRs failing on linting
=> fix linting by using new maligned linter instead of aligncheck

s3/public.go, s3/public_test.go
DELETE requests, both for temporary files and no longer referenced
packages, lacked the configured path prefix and therefor were not
removed if a prefix is configured.
Adds the path prefix to Remove() so that temporary and unreferenced pool files are properly removed.
=> S3 backend: include path prefix in removal requests.

aptly/interfaces.go, cmd/mirror_update.go, context/context.go, deb/package.go, deb/remote.go, http/compression.go, http/compression_test.go, http/download.go, http/download_test.go, http/fake.go, http/temp.go, http/temp_test.go
There are two fixes here:
1. Abort package download immediately as ^C is pressed.
2. Import all the already downloaded files into package pool,
so that next time mirror is updated, aptly won't download them
once again.
Fixes #545
=> Use Go context to abort gracefully mirror updates

api/graph.go, api/publish.go, api/repos.go, api/snapshot.go
Fixes #686
LoadComplete() modifies object, so it would cause issues if it runs
concurrently with other methods. Uprage mutex locks to write
locks when LoadComplete() is being used.
This reduces concurrency of some API calls but eliminates data races
=> Fix race in API related to `LoadComplete()`

deb/index_files.go, files/public.go, files/public_test.go
the logic here was wrong.
if we managed to find the link target (the physical index file) pointed to
by our old symlink we want to remove it (this is basically "cleaning up old
index" logic).
previously we'd try to only delete it when the ReadLink came back with
error. which had two serious issues with it:
a) linkTarget was empty, so we basically called Remove("") which would
delete the storage -> root <- directory if the root is a symlink!
b) we'd leak old indexes as the cleanup logic only ran if there was en
error which would ordinarily never be
new code correctly cleans up unless there was an error.
readlink was also entirely wrong and adjusted to work correctly within the expectations of a …
=> Fix by by-hash index cleanup + root dir data "loss"

files/public.go, files/public_test.go
presently there is no use case where we need this. on the other hand,
passing empty paths into any of the remove methods is indicative of a bug.
this is particularly dangerous as this can temporarily smash the publish
root but later restore it again when actually publishing. this makes
for super nasty and hard to track down problems.
to guard against this simply disallow root dir removal using empty
strings. should we find a use case for this in the future we can always
revisit this (FTR: I think very explicitly API should be used so everyone
knows what is going on and you can't accidentally run it)
=> prevent removal of a PublishedStorage's root dir

deb/publish.go
updates with contents generation were super syscall-heavy. for each path
in a package (so at least 2-4, but ordinarily >4) we'd do a db.Put in
ContentsIndex which results in one syscall.Write. so, for every package in
a published repo we'd have to do *at least* 2 but ordinarily >4 syscalls.
this gets abysmally slow very quickly depending on the available system
specs.
instead, start a batch inside each package and finish it when we are done
with the package. this should keep the memory footprint negligible, but
reduce the write() calls from N to 1.
on one of KDE's servers I have seen update publishing of 7600 packages go
from ~28s to ~9s when using batch putting on an HDD.
on my local system the same set of packages go from ~14s to ~6s on an SSD.
(all inodes in cache in both cases)
=> batch updates to the temporary db when publishing

Gopkg.lock, deb/contents.go, deb/index_files.go, deb/publish.go, system/t06_publish/PublishRepo1Test_contents_i386_legacy, system/t06_publish/repo.py, system/t06_publish/snapshot.py, system/t06_publish/switch.py, system/t06_publish/update.py
Another index is created which unifies data for all the components.
This certainly requires more resources as we have to build yet another
index.
Fixes #667
=> Implement 'legacy' Contents indexes to match Ubuntu <=16.04

aptly-api.service, aptly.service
Provides a systemd service file for `aptly serve` command.
This file can be placed in `/etc/systemd/system/` (for users/administrators) or `/lib/systemd/system/` (for distributions).
Extra configuration options should be specified in a `.conf` inside `/etc/systemd/systemd/aptly.service.d/`
=> Add systemd service for aptly http server

.gitignore, .travis.yml, Makefile, README.rst
1. Don't run long steps for Go versions other than 1.9 & 1.10
according to Golang Release Policy (two latest versions).
2. Switch to codecov.io, collect coverage only on Go 1.10 which
has fixes for multi-module coverage & ./... ignoring vendor.
3. Simplify Makefile.
=> Change build settings to speed up builds

.gitignore, .travis.yml, Makefile
- new phony target build: same as install but creating aptly-$version and
putting it into a build/ subdir
- env TRAVIS_TAG in the makefile now overrides the TAG lookup, this ensures
that the tag travis is working with is actually the one being used to
construct the version number
- subdir is gitignored
- travis runs new target - lists artifacts - deploys artifacts to github
all of the above only happens on builds that are a tag and DEPLOY_BINARIES
is set to yes (which is only the case for latest stable go version)
=> add support for travis attaching build artifacts to releases

pgp/gnupg.go
This allows to force using GnuPG 2.x even if aptly is not 100% ready
to use it.
See #741, #657
=> Skip GPG version check `APTLY_SKIP_GPG_VERSION_CHECK=1` is set in the env

deb/index_files.go, system/t06_publish/repo.py, system/t06_publish/snapshot.py, system/t06_publish/switch.py, system/t06_publish/update.py
Fixes: #756
See #756 for detailed description
=> Keep checksum of not compressed index file even if it's not uploaded

cmd/db_cleanup.go
This is not a complete fix, but the easiest first step.
During `db cleanup`, aptly is loading every repo/mirror/... into memory,
and even though each object is processed only once, collection holds
a reference to all the loaded objects, so they won't be GC'd until
process exits.
CollectionFactory.Flush() releases pointers to collection objects,
making objects egligble for GC.
This is not a complete fix, as during iteration we could have tried
to release a link to every object being GCed and that would have
helped much more.
See #761
=> Lower memory usage for `aptly db cleanup`

deb/local.go, deb/publish.go, deb/remote.go, deb/snapshot.go, deb/snapshot_bench_test.go
See #761
aptly had a concept of loading small amount of info per each object
into memory once collection is accessed for the first time.
This might have simplified some operations, but it doesn't scale well
with huge aptly databases.
This is just intermediate step towards better memory management -
list of objects is not loaded unless some method is called.
`ForEach` method (mainly used in cleanup) is reimplemented to
iterate over database without ever loading all the objects into memory.
Memory was even worse with previous approach, as for each item usually
`LoadComplete()` is called, which pulls even more data into memory
and item stays in memory till the end of the iteration as it is referenced
from `collection.list`.
For the subsequent PR: reimplement `ByUUID()` and probably other …
=> Implement lazy iteration (ForEach) over collections

Makefile, deb/local.go, deb/local_test.go, deb/remote.go, deb/remote_test.go, deb/snapshot.go, deb/snapshot_bench_test.go, deb/snapshot_test.go
See #765, #761
Collections were relying on keeping in-memory list of all the objects
for any kind of operation which doesn't scale well the number of
objects in the database.
With this rewrite, objects are loaded only on demand which might
be pessimization in some edge cases but should improve performance
and memory footprint significantly.
This doesn't touch `PublishedRepoCollection` as it relies on list of 
all the objects in many places to implement unique checks, proper
cleanup.
=>  Reimplement DB collections for mirrors, repos and snapshots

CONTRIBUTING.md
Fixes: `make install` will fail when following the current CONTRIBUTING.md
```
❯ make install
go install -v -ldflags "-X main.Version=1.3.0+30+g72ff71f"
main.go:8:2: cannot find package "github.com/aptly-dev/aptly/aptly" in any of:
/home/steven/osrf/aptly_gopath/src/github.com/smira/aptly/vendor/github.com/aptly-dev/aptly/aptly (vendor tree)
/usr/lib/go-1.10/src/github.com/aptly-dev/aptly/aptly (from $GOROOT)
/home/steven/osrf/aptly_gopath/src/github.com/aptly-dev/aptly/aptly (from $GOPATH)
main.go:9:2: cannot find package "github.com/aptly-dev/aptly/cmd" in any of:
/home/steven/osrf/aptly_gopath/src/github.com/smira/aptly/vendor/github.com/aptly-dev/aptly/cmd (vendor tree)
/usr/lib/go-1.10/src/github.com/aptly-dev/aptly/cmd (from $GOROOT) …
```
=> Use github.com/aptly-dev/aptly as the go package path.

AUTHORS, README.rst
Documentation should be updated. CI should pass.
Old project for run docker w aptly not supported long time.
All functional doesn't work.
I create updated and worked fork based on original repo Bryan Hong.
=> Replace Docker container w aptly & nginx in README

upload-artifacts.sh
This breaks releases, as two versions of the package with same version
might end up in internal.aptly.info.
=> Skip uploading release versions of aptly to nightly repo

cmd/api_serve.go
See PR #807
Fixes: #849
This reverts commit 22848b010d55b818f3d03fdbca02a67bc8ee225b.
=> Revert "Don't remove API file socket if it exists and it's usable"

api/repos.go, aptly/interfaces.go, cmd/mirror_update.go, cmd/repo_add.go, cmd/repo_include.go, database/database.go, deb/changes.go, deb/changes_test.go, deb/checksum_collection.go, deb/collections.go, deb/import.go, deb/local.go, deb/local_test.go, deb/package_collection.go, deb/publish.go, deb/remote.go, deb/remote_test.go, deb/snapshot.go, deb/snapshot_test.go
For any action which is multi-step (requires updating more than 1 DB
key), use transaction to make update atomic.
Also pack big chunks of updates (importing packages for importing and
mirror updates) into single transaction to improve aptly performance and
get some isolation.
Note that still layers up (Collections) provide some level of isolation,
so this is going to shine with the future PRs to remove collection
locks.
Spin-off of #459
=> Consistently use transactions to update database

context/context.go, man/aptly.1, man/aptly.1.ronn.tmpl, system/lib.py, system/t02_config/ConfigShowTest_gold, system/t02_config/CreateConfigTest_gold, system/t02_config/aptly.conf, utils/config.go, utils/config_test.go
This makes the global command line flag `-db-open-attempts` a configuration option in aptly.conf (as `databaseOpenAttempts`).
We'd rather configure it there instead of adding the flag to every invocation of aptly in our CI/CD setup.
I couldn't test this change thoroughly, but I oriented on how it was done for other, similar flags/options.
Thanks!
=> Make database open attempts configurable also via config file

deb/remote.go, http/download.go
Part of PR #459
This prepares for more methods to be exposed via the API.
=> Fix issues with `progress == nil` causing panics

.travis.yml, README.rst
This might allow to switch to Go modules as the next step.
=> Bump Go supported version to 1.11-1.13

AUTHORS, deb/version.go, deb/version_test.go
This commit closes: #145
The dependency format "pkg:arch" (e.g. "python3:any") was not well parsed if not any version is given. This commit splits the dependency name and architecture in all cases.
=> Parse dependency architecture even without version

go.mod, go.sum
PR #876 actually upgraded goleveldb to 1.0.0, not to the latest master.
Recent changes to goleveldb should improve performance
https://github.com/syndtr/goleveldb/issues/226#issuecomment-477568827
=> Really upgrade goleveldb to the latest master version

AUTHORS, pgp/gnupg_finder.go
This changes GPGFinder to allow for nonstandard version strings.
Specifically, I have MacGPG installed instead of upstream GPG, which results in the version string reading `gpg (GnuPG/MacGPG2) 2.2.17` instead of the expected `gpg (GnuPG) 2.2.17`
----
I'm not sure if the unchecked items are applicable. A unit test could probably be added, though I'm not entirely sure how other than possibly making a mock binary that responds to `--version` with the MacGPG version string and adding it to the test-bins.
=> Allow GPGFinder to work with nonstandard GPG version strings

.travis.yml, go.mod, system/t04_mirror/create.py
Fixes #939
Test against newer versions of Go.
=> Test against newer versions of Go

s3/public.go
The S3 backend relies on ETag S3 returns being equal to the MD5 of the object, but it’s not necessarily true. For that purpose we store the MD5 object in a separate metadata field as well to make sure it isn’t lost. When the value returned clearly doesn’t look like a valid MD5 hash (length isn’t exactly 32 characters), attempt to retrieve the MD5 hash possibly stored in the metadata.
We cannot always do this since user-defined metadata isn’t returned by the ListObjects call, so verifying it for each object is expensive as it requires one HEAD request per each object.
This pull request fixes #923
=> Store MD5 in a separate metadata field and use it when ETag is not an MD5 hash

.goxc.json
Go 1.15 drops support for darwin/386 GOOS/GOARCH pair [1]. So, we have
to skip this pair, and thus cannot use simple os multiply arch anymore.
Switch to goxc's BuildConstraints config, which uses the same syntax as
Go's build constraint header [2].
[1] https://github.com/golang/go/issues/37610
[2] https://golang.org/cmd/go/#hdr-Build_constraints
Fixes #943
=> .goxc.json: list os/arch explicitly to avoid darwin/386

README.rst, pgp/gnupg.go, pgp/internal.go
Fixes #990 - the not so much experienced users are confused by cryptic error message
This is only minor change. No extra requrements
The current example uses  pool.sks-keyservers.net that is no longer operating. The new one is working well:
```shell
repo@apt:~/bin$ gpg --no-default-keyring --keyring trustedkeys.gpg --keyserver pool.sks-keyservers.net --recv-keys CE1A3DD5E3C94F49
gpg: keyserver receive failed: No name
repo@apt:~/bin$ 
repo@apt:~/bin$ gpg --no-default-keyring --keyring trustedkeys.gpg --keyserver keyserver.ubuntu.com --recv-keys CE1A3DD5E3C94F49
gpg: key CE1A3DD5E3C94F49: public key "MariaDB Enterprise Signing Key <signing-key@mariadb.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```
=> Proposed keyserver changed to functional one

deb/remote.go
Export the package list of a remote repository
=> Export RemoteRepo package list

.github/workflows/ci.yml, Makefile, system/fs_endpoint_lib.py, system/lib.py, system/run.py, system/s3_lib.py, system/swift_lib.py, system/t04_mirror/update.py, system/t06_publish/repo.py, system/t06_publish/snapshot.py, system/t06_publish/switch.py, system/t06_publish/update.py, system/t07_serve/__init__.py, system/t09_repo/add.py, system/t09_repo/cmdimport.py, system/t09_repo/copy.py, system/t09_repo/include.py, system/t09_repo/move.py, system/t09_repo/remove.py, system/t12_api/graph.py, system/t12_api/mirrors.py, system/t12_api/packages.py, system/t12_api/repos.py, system/t12_api/snapshots.py, system/t12_api/systemd_handover.py, system/t12_api/tasks.py, system/t12_api/unix_socket.py
Fixes #938
Use Python 3.9+ for tests
=> Convert tests to Python 3

CONTRIBUTING.md
=> Fix: typo in aptly web page link

system/t04_mirror/CreateMirror27Test_gold, system/t04_mirror/CreateMirror27Test_mirror_show, system/t04_mirror/create.py
Fixes #1034 
Use mirror instead of official linux.dell.com repo, which is often down.
=> Use University of Utah mirror in tests

.github/workflows/ci.yml
Fix #1032
Fixes #
Add a 30 minutes timeout to CI build test, to avoid runaway tests.
Currently sane unittests run in less than 10 minutes.
=> Timeout CI build job after 30 minutes

README.rst
Using the gpg key in the README:
```shell
Err:1 http://repo.aptly.info squeeze InRelease                                                         
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EE727D4449467F0E
```
The actual repo uses different gpg key. Either the repo has been taken over, or the README is out of date.
=> Update the gpg key of the `repo.aptly.info` repository in the README

.github/workflows/ci.yml, upload-artifacts.sh
#920 
We moved the whole aptly infrastructure to our own infrastructure and moved `internal.aptly.info` to `aptly-ops.aptly.info`
so we can publish new releases there. :tada:
=> Publish releases and nightly builds from ci

.github/workflows/ci.yml, upload-artifacts.sh
=> Fix artifacts publishing

AUTHORS, azure/public.go, azure/public_test.go, context/context.go, man/aptly.1, man/aptly.1.ronn.tmpl, utils/config.go, utils/config_test.go
Add custom endpoint config for publishing to Azure blob storage. This is needed to support publishing to Azure sovereign clouds, i.e. China, Germany, and the US government. The change also made it possible to test the Azure publishing via [the Azure storage emulator](https://github.com/Azure/Azurite) by setting the endpoint to the local emulator address.
- ~~[ ] functional test added/updated (if change is functional)~~
- ~~[ ] bash completion updated (if applicable)~~
=> Support custom Azure publish endpoint

AUTHORS, cmd/publish_list.go
This PR is a workaround for #428.
The idea is to have information about publish which is in trouble and to be able to drop it and to re-publish it.
=> Give info when unable to load list of repos

AUTHORS, deb/query.go, deb/query_test.go, deb/version_test.go
Reopen of https://github.com/aptly-dev/aptly/pull/1065 after messed up rebase.
@russelltg sorry about that but please use `git pull --rebase` in the future to avoid having strange merge commits in the history ;)
=> Use correct version compare

.github/workflows/ci.yml
Enable Azure publishing unit tests in Github actions using Azure storage emulator (https://github.com/Azure/Azurite). 
Ensure Azure publish APIs are tested in CI jobs.
Including Azurite in CI also enables adding system tests for Azure publishing functionalities in the future. Since there are already some issues (e.g., https://github.com/aptly-dev/aptly/issues/1060) reported on the Azure publish command, I plan to add system tests to cover common usages.
=> Enable Azure publish unit tests in Github actions

.github/workflows/ci.yml
By default Azurite action runs under `/tmp`. The directory is not stable between jobs. (I saw files under `/tmp` being cleared between jobs.) This has caused CI job failures in recent pull requests that added Azure system test, e.g. https://github.com/aptly-dev/aptly/actions/runs/2352295323. This change fixes the issue by setting the Azurite running directory to the runner temp directory.
=> Fix azurite dir for CI

api/router.go
Aptly allows create e.g. repos with a / to use those with the REST api
the router needs to allow urlencoded parameters in various places to
represent this. A specific example of this is the /api/repos/:name/packages path
Signed-off-by: Sjoerd Simons <sjoerd@collabora.com>
=> api: allow parameters with urlencoded names

Makefile
Most modern distribution use python3 for python (3). Default to that to
make it a bit simpler to run systems tests on Debian
Signed-off-by: Sjoerd Simons <sjoerd@collabora.com>
=> Use python3 for system tests

http/download.go
Fixes #999
Cope with web servers responding with HTTP Code 200 but no Content-Length header for zero-length files.
=> Cope with zero-length http downloads w/o Content-Length header

.github/workflows/ci.yml, codecov.yml
Renable code coverage reports https://app.codecov.io/gh/aptly-dev/aptly/
=> Upload code coverage

AUTHORS, man/aptly.1, man/aptly.1.ronn.tmpl, s3/public.go
This change lets you disable ACL when using S3 by using a configuration
value of `none`. This way we maintain backward compatibility with the
default setting being `private`.
Fixes: #1067
=> S3: support disabling ACL with `none` value

.github/workflows/ci.yml, api/publish.go, system/t04_mirror/ShowMirror8Test_gold, system/t04_mirror/show.py
Fixes #1097 wich was introduced with https://github.com/aptly-dev/aptly/commit/f61514edaf23c1084e185ee16a413bcee8de9cc9#diff-be026efeb4b3190a57554a1cff89f6b726ffb0380519517eecd68e8647a89387R214
=> Fix wrong nil check for SkipBz2

api/packages.go, api/router.go, system/t12_api/packages.py
The ".../packages" endpoints for mirror, local repos and snapshots all
share the same syntax for querying. However the "/api/packages" endpoint
doesn't match this. Adjust that to allow for a bit more consistency and
allow querying the full package database.
The current endpoint functionality "/packages/:name" is kept intact and
can be used the same as now
Signed-off-by: Sjoerd Simons <sjoerd@collabora.com>
=> api: Allow querying the packages endpoint

AUTHORS, cmd/publish_repo.go, cmd/publish_snapshot.go, completion.d/_aptly, completion.d/aptly, deb/publish.go, man/aptly.1, system/t06_publish/PublishList5Test_gold, system/t06_publish/PublishShow3Test_gold, system/t06_publish/PublishShow4Test_gold, system/t06_publish/PublishSnapshot1Test_release_amd64, system/t06_publish/PublishSnapshot1Test_release_i386, system/t06_publish/PublishSnapshot35Test_release_udeb_i386, system/t06_publish/PublishSnapshot39Test_release_amd64, system/t06_publish/PublishSnapshot39Test_release_i386, system/t12_api/publish.py
This is a continuation on #892, but rebased and with fixed system tests so that it is hopefully closer to being ready for merging. With many thanks to @smstone for the work on this feature.
_Original description:_
This change will allow users to set a custom Codename in the release files when publishing.
This PR is inspired/guided by https://github.com/aptly-dev/aptly/pull/874
While testing out Aptly, our test apt-get clients were exiting with non-zero status since Codename was changed in the release files that are baked out by Aptly:
```
E: Repository 'http://debianrepo.example.com/bionic unstable InRelease' changed its 'Codename' value from '' to 'unstable'
N: This must be accepted explicitly before updates for this repository can be applied. See …
```
=> Allow custom codename

AUTHORS, context/context.go, man/aptly.1, man/aptly.1.ronn.tmpl, s3/public.go, s3/public_test.go, utils/config.go, utils/config_test.go
Some of s3 style store not support path style, need a option to control it
=> add forceVirtualHostedStyle for stores which only support virtual hosted style

api/task_test.go, task/list.go
All other api endpoints also send empty arrays instead of nil. Closes #1123
Fixes #1123
Returns an empty array instead of nil if there are no tasks available
=> Return an empty array if no tasks are available

AUTHORS, api/api_test.go, api/router.go
If aptly.EnableDebug is active, we use gin.DebugMode, otherwise we use gin.ReleaseMode to remove the annoying nudging messages when running the api.
Fixes #1103
We now change the gin Mode before instantiating the server.
--> Performance of the API is improved in Release mode
--> No more annoying messages when running `aptly api serve`
=> Fix: Switch gin mode depending on aptly.EnableDebug

api/publish.go
Fixes #1006 
Deleting a publish that does not exist now results in a status code 404 instead of 500.
--> Status code 500 should be avoided if another status code represents the issue better to the consumer of the API.
=> Fix: Drop Publish returned wrong status code if not found

codecov.yml
Fixes #1154 
The CodeCov Pipeline will now only fail if the code coverage has fallen more than 2 percent with that Pull Request.
--> The pipeline should now no longer fail and block pull requests when only small fixes were applied
=> Fix: Make CodeCov pipeline non-blocking

api/router.go, api/snapshot.go, system/t12_api/snapshots.py
Is part of Issue #176
I added the API `POST /api/snapshots/merge` to create a new snapshot from several others, analogous to the `aptly snapshot merge` command. 
(This is my first Aptly feature, please tell me if something's missing : ) )
--> Useful for remote management.
=> Feature: Add Merge Snapshot API

go.mod, go.sum
Older versions go-xz didn't wait for child processes meaning for exery unpack action a defunct xz would stick around. This got fixed in 0.1.0
=> Update go-xz to 0.1.0

AUTHORS, deb/graph.go
This helps visually distinguish between local publications and those on S3.
In PR, I changed publish name function to `repo.GetPath()` ([source](https://github.com/aptly-dev/aptly/blob/9c6f8966664a77b5e5989a383dcf2175c5c8b15c/deb/publish.go#L526)) which returns the same data (`repo.Prefix`, `repo.Distribution`), but also return storage if exists.
For visualization. In master:
In PR:
=> Print publish storage on graph

AUTHORS, api/mirror.go
When trying to delete a mirror that has snapshot and not providing the force option, the API should not return a `500
StatusInternalServerError`.
A `403 StatusForbidden` is more appropriate when the condition is expected by the server.
Fixes #
I was able to run `make modules install` and `make test` with success but I'm not able to run `make system-test` because of missing dependencies (gpg1).
When implementing a client for Aptly API the `500` HTTP status code returned does not make it clear that there is an issue with the request.
From https://www.rfc-editor.org/rfc/rfc9110.html#name-500-internal-server-error
> [15.6.1. ](https://www.rfc-editor.org/rfc/rfc9110.html#section-15.6.1)[500 Internal …
=> Fix returncode when deleting a mirror with snapshot

api/publish.go, pgp/internal.go
It doesn't make sense to expose the Batch option, which, if `false` enables input from stdin for gpg passphrases, which blocks the api thread. Because of this, I removed the option, and set it to `true` by default.
* Remove `Batch` option
* Set `Batch` to true internally
So the API can't get hung up because a user tries to sign a publish with a key that requires a passphrase he didn't provide in the request.
=> Fix: Remove Batch from API options, set to true by default

AUTHORS, system/lib.py
From the first commit:
```
The current regex runs in exponential time, which massively impacts the
runtime of the test suite, taking several seconds (~4s on my system)
just to perform a single match. By replacing the mix of re.findall + the
initial capture group with re.search + some string slicing, the time
spent matching the regex becomes nearly instant, e.g.:
$ make system-test TESTS='Config*'
goes from taking ~10s to ~1.5s.
```
=> Improve test output regexes for better perf and Go 1.20 support 

cmd/api_serve.go
This will properly close the db and, more particularly, flush out any profile files being written. Otherwise, they can end up empty or truncated.
=> Shut down cleanly when 'api serve' is interrupted

.github/workflows/golangci-lint.yml, Makefile, aptly/const.go, deb/index_files.go, deb/package.go, deb/publish.go, deb/remote.go
=> Fix the installer path for Ubuntu Focal

api/router.go, api/s3.go
allow to query the available s3 buckets, so the information can be used by subsequent api calls.
=> s3 api: get publish root list

api/gpg.go
Self signed GPG keys were refused, which is something aptly should allow, if a repo for mirroring is singed this way.
Also, use the default GPG version, as in the other parts for using GPG keys.
The API also returns the gpg command output, instead of just a failure.
=> gpg api: allow self signed and use default gpg version

api/files.go, deb/changes.go, deb/import.go, deb/publish.go, deb/publish_bench_test.go, deb/publish_test.go, deb/reflist.go, deb/reflist_bench_test.go, deb/remote_test.go, files/package_pool.go, files/public.go, go.mod, go.sum
Replaces #1222
This contains a variety of improvements for publish performance, specifically speeding up the cleanup operation by:
- using a separate, faster package to walk the filesystem
- avoiding re-loading the same packages repeatedly (this will happen if a single prefix has a large number of snapshots or repos that share most of their packages)
- slightly improving the package list loading performance w/ zero-copy deserialization
Benchmarks were added for all of these, and some unit tests were added specifically to test aspects of cleanup.
We have a relatively large aptly repository with >90 repositories, ~207k packages across all of the repositories, and >3.5k snapshots; a testing version of …
=> Improve publish performance, especially for prefixes with a large number of snapshots

api/publish.go, cmd/publish_list.go, deb/publish.go
Replaces #1227
Loading the reflists to list publish information takes a significant amount of time, even though the resulting info doesn't actually use any of the reflists.
=> Skip loading reflists when listing published repos

http/download_test.go, http/grab_test.go
Replaces #1231
on hosts which have wildcard dns domains in their local domain search list, builds failed because "nosuch.host" could actually be resolved.
Since ".host" isn't a recommended TLD by RFC2606, we use ".invalid" now. And since this is not enough to fix the problem, we use now absoulte domain names (having a '.' at the end)
Fixes #1230
=> fix failing build on hosts with wildcard dns (fixes #1230)

AUTHORS, api/mirror.go
Fixes #
The command line flags `-force-architectures` and `-ignore-signatures` are not consistently implemented in the mirror API like they are in the mirror CLI. Discovered because the example repo I'm attempting to use, `https://pkg.duosecurity.com/Ubuntu`, is non-standard and breaks without these specified.
`SkipArchitectureCheck` and `IgnoreSignatures` are implemented as params for the create/POST and update/PUT handlers under `/api/mirrors`. 
Did not implement unit tests as there doesn't appear to be a good harness for mocking downloads.
Updating functional tests would be nice, seems we can add to https://github.com/aptly-dev/aptly/blob/master/system/t12_api/mirrors.py if we potentially upload …
=> Enable SkipArchitectureCheck and IgnoreSignatures in mirror API

AUTHORS, api/publish.go, cmd/publish_repo.go, cmd/publish_snapshot.go, cmd/publish_switch.go, cmd/publish_update.go, completion.d/aptly, deb/publish.go, deb/publish_test.go
This change makes it possible to publish multiple distributions with packages named the same but with different content by changing structure of the generated pool hierarchy. The option not enabled by default as this changes the structure of the output which could break the expectations of other tools.
Fixes #486 
Given #486 and and [this discussion on aptly-discuss](https://groups.google.com/g/aptly-discuss/c/YTLXLUqBbFo) it seems I am not alone in using aptly to self-publish some packages for a handful different distributions and wanting to publish different packages with the same filename for different distributions. As it stands, due to aptly using the default directory structure for the `pool` …
=> Introduce option `-multi-dist` to the publish commands

s3/public.go, s3/public_test.go
Fixes https://github.com/aptly-dev/aptly/issues/1117
If the S3 bucket used to house a repo has KMS encryption enabled then the etag of an object may not match the MD5 of the file. This may cause an incorrect error to be reported stating the file already exists and is different.
A mechanism exists to work around this issue by using the MD5 stored in object metadata. This check doesn't always cover the case where KMS is enabled as the fallback is only used if the etag is not 32 characters long.
This commit changes the fallback mechanism so that it is used in any case where the object's etag is not 32 characters _or_ if the S3 bucket has encryption enabled for new objects by default.
=> Check both MD5 locations for S3 KMS support.

api/api.go, api/api_test.go, api/packages_test.go, system/t12_api/repos.py
repo and snapshots packages filter api add 'maximumVersion' query parameter support
example: `curl http://localhost:8080/api/repos/test/packages\?maximumVersion\=1`
Change-Id: Ie9ffd36146bf017bbb353737f32360f7b73d6b0a
Replaces #1088
=>   repo and snapshots packages filter api add 'maximumVersion' query parameter support 

api/mirror.go, cmd/mirror.go, cmd/mirror_create.go, cmd/mirror_edit.go, cmd/mirror_update.go, cmd/repo_include.go, deb/remote.go, deb/remote_test.go, pgp/gnupg.go, pgp/gnupg_test.go, pgp/internal.go, pgp/internal_test.go, pgp/pgp.go, system/t04_mirror/CreateMirror33Test_gold, system/t04_mirror/CreateMirror33Test_mirror_show, system/t04_mirror/create.py
Fixes #237
If a remote repo has only InRelease but no Release file, aptly is not able to mirror it, even when -ignore-signatures is specified.
This change fixes this behavior, by trying to download the InRelease if Release file is not found, and strips and ignores the signature.
=> fix ignoring signatures on remote repos with only InRelease file

api/api_test.go, api/repos.go, api/router.go, system/t12_api/repos.py
In case we don't have the possibility to use the `aptly` CLI on a repository, expose the `aptly copy` command through the REST API.
=> Expose the copy package operation through REST API

CONTRIBUTING.md
Explicitly state that Python3 is supported and required.
Since aptly `v1.5.0` (with commit 035d5314b08263a20059f8bfca6f7524e5a80cb4) the tests are ported to Python3.
With a687df2f4f44a87670570ecc9a7fe137f1bac270 the system tests are run with `python3` per default.
With f4a152ab228442acd40d6cb49fcc8e99307519c9 (after `v1.5.0` aptly tag) the tests run against Python 3.11.
- I don't think this little change warrants my addition to the AUTHORS file
=> CONTRIBUTING: Python3 is supportet

api/api.go
Fixes #1323
since sync API calls also use tasks internally, this lead to out of memory due to aptly never removing them.
This change fixes this behavior and deletes the internal task with sync calls.
=> api: fix OOM with sync tasks

Makefile, api/mirror.go, api/router.go, api/snapshot.go, system/t12_api/gpg.py, system/t12_api/snapshots.py
- provide snapshot pull api
- use proper REST api for snapshot merge
- **this breaks the existing snapshot merge  api, which is only available in CI builds**
- improve swagger doc
=> Snapshot Pull API

api/files.go, api/gpg.go, api/publish.go, api/repos.go, go.mod, utils/utils.go
API parameters might be used for filesystem operations, and CodeQL complains about potential path traversal issues. 
This change introduces PathSanitize which removes any leading slashes and `..` from the parameter.
about 30 CodeQL complaints are addressed.
=> fix path traversal

AUTHORS, api/repos.go, system/t12_api/repos.py
To achieve feature parity with cli, it is now possible to create repos from snapshots.
=> Update create repo API to support snapshots

deb/import.go, deb/list.go, deb/list_test.go, deb/reflist_test.go, system/t09_repo/AddRepo8Test_gold
the error message "conflict in package" is due to the package already existing but being different (hash, ..). this change makes the error message more specific.
=> repo add: improve error message

api/publish.go, api/repos.go, api/snapshot.go
Fixes https://github.com/aptly-dev/aptly/issues/1376
- fix race condition with rasync background operations
- Do all relevant database reading inside `maybeRunTaskInBackground`.
- Notably, `LoadComplete` will load the reflist of a repo. if this is done outside of a background operation, the data might be outdated when the background tasks runs.
=> Fix race condition with async API operations

deb/package.go, system/t05_snapshot/VerifySnapshot7Test_gold
While trying to debug #1378, I noticed that my new version of `providesDependency` is probably wrong.
In the case when the `Provides` entry does not specify a version, calling `providesDependency` with `VersionEqual` as the relation would return `false`, IDK if this is the correct behavior. I think the correct behavior would be to use the version specified in the `Version` field in this case.
Also, it was only considering the `Relation` of the `Provides:` entry instead of the relation of the actual dependency it seems.
Could you please check this?
=> package.go: Fix bug in providesDependency

cmd/api_serve.go, context/context.go, http/download.go, http/download_test.go
Fixes #1335 
This code change prevents SIGINT/SIGTERM signals from stopping the Aptly API server before it has cleaned up any resource locks in the database. Normally for CLI aptly commands, it would clear these locks if it detects the PID that had the previous lock is no longer running. However, if Aptly is running as an API server in a container, it always runs as PID 1, which means the PID no longer works as a unique identifier to detect what is running at any given time, leaving these locks indefinitely.
Even with this MR, this issue can still present itself if an Aptly container is SIGKILLed (docker rm -f), however that is a more difficult problem to solve that would likely take some significant rearchitecting (since the API was tacked on to aptly after the fact).
=> Make HTTP server wait for tasks before shutdown

deb/publish.go
This commit fixes a null pointer when a multi-dist published repo gets dropped.
Signed-off-by: Christoph Fiehe <c.fiehe@eurodata.de>
=> Fix: Null pointer when dropping a multi-dist published repo

AUTHORS, api/api.go, api/mirror.go, api/repos.go, api/snapshot.go, cmd/repo_move.go, cmd/repo_remove.go, cmd/snapshot_filter.go, cmd/snapshot_pull.go, cmd/snapshot_search.go, deb/list.go, deb/list_test.go, deb/package.go, deb/remote.go, system/t04_mirror/UpdateMirror10Test_gold, system/t06_publish/snapshot.py
Fixes #1403
This fixes a bug where aptly doesn't behave as specified in the documentation.
The core of the change is to just add an option to `Filter` to indicate that source packages need to be included and, if that option is set, add the missing packages to the result.
```diff
--- a/deb/list.go
+++ b/deb/list.go
@@ -524,6 +537,37 @@ func (l *PackageList) Filter(options FilterOptions) (*PackageList, error) {
for _, query := range options.Queries {
_ = result.Append(query.Query(l))
}
+ // The above loop already finds source packages that are named equal to their binary package, but we still need
+ // to account for those that are named differently.
+ if options.WithSources {
+         sourceQueries := make([]PackageQuery, 0)
+         for _, pkg := range result.packages {
+ …
```
=> Fix `-with-sources` not fetching differently named source packages

cmd/cmd.go, cmd/mirror_create.go, cmd/mirror_edit.go, cmd/package_search.go, cmd/package_show.go, cmd/repo_move.go, cmd/repo_remove.go, cmd/snapshot_filter.go, cmd/snapshot_pull.go, cmd/snapshot_search.go, cmd/string_or_file_flag.go, man/aptly.1, system/t03_help/MirrorCreateHelpTest_gold, system/t03_help/MirrorCreateTest_gold, system/t03_help/WrongFlagTest_gold, system/t04_mirror/CreateMirror36Test_gold, system/t04_mirror/CreateMirror36Test_mirror_show, system/t04_mirror/CreateMirror37Test_gold, system/t04_mirror/CreateMirror37Test_mirror_show, system/t04_mirror/create.py
Fixes #1409
As mentioned in the Issue, we have filter expressions that exceed the command line length limit and thus need to be read from a file/stdin. This PR extends the Aptly command-line interface to be able to read filter expressions from a file using the `@/path/to/file` syntax or `@-` for stdin.
Our use case is only for the `-filter` argument for `mirror create`/`mirror edit`. However, there are other places in Aptly where filter expressions are accepted, so I added support for the `@file` syntax everywhere for consistency.
Commands where the `@file` syntax is supported now:
- `mirror create`
- `mirror edit`
- `package search`
- `package show`
- `repo move`
- `repo remove`
- `snapshot …
=> Feature: Support Reading Filter Expressions from a File

cmd/cmd.go, cmd/mirror_create.go, cmd/mirror_edit.go, cmd/package_search.go, cmd/package_show.go, cmd/repo_move.go, cmd/repo_remove.go, cmd/snapshot_filter.go, cmd/snapshot_pull.go, cmd/snapshot_search.go, cmd/string_or_file_flag.go, man/aptly.1, system/t03_help/MirrorCreateHelpTest_gold, system/t03_help/MirrorCreateTest_gold, system/t03_help/WrongFlagTest_gold, system/t04_mirror/CreateMirror36Test_gold, system/t04_mirror/CreateMirror36Test_mirror_show, system/t04_mirror/CreateMirror37Test_gold, system/t04_mirror/CreateMirror37Test_mirror_show, system/t04_mirror/create.py
=> COVERAGE Filter using file

README.rst, deb/snapshot.go, system/t05_snapshot/CreateSnapshot10Test_gold, system/t05_snapshot/create.py
Fixes https://github.com/aptly-dev/aptly/issues/1416
- allow to create snapshots of empty mirrors
- add test
=> Allow snapshotting empty mirrors

debian/aptly-api.postrm
according to debian policy, purge should leave no trace. 
this change removes the user and aptly data on apt-get purge.
See: https://piuparts.debian.org/sid-strict/fail/aptly-api_1.6.0+ds1-3.log
=> postrm: remove aptly-api user and home directory on purge

completion.d/aptly
Fixes #
This patch enhances the Aptly bash‐completion script by collecting and
reusing any global options passed to `aptly` so that completions work
correctly when users supply flags such as `--config`, `--architectures`,
`--gpg-provider`, etc.
Key changes:
- Introduce `aptly_global_opts` array to accumulate recognized global options.
- Implement path‐completion (`_filedir`) for options in `options_with_path_arg`.
- Fix typo where `compopt` was misspelled as `comptopt`.
=> bash-completion: include global options in aptly command completions

.github/workflows/ci.yml, Makefile, api/gpg.go, api/repos.go, system/Dockerfile, system/lib.py, system/run.py, system/s3_lib.py, system/t04_mirror/create.py
Fixes #1447
Document adding GPG keys to aptly keyring, fix /api/repos documentation, cleanup swagger validation errors.
=> doc: add swagger doc for /api/gpg/key

AUTHORS, files/linkfrompool_concurrency_test.go, files/public.go
This fixes the race condition that happens when you call publish concurrently. It adds a valuable test that reproduces the error almost deterministically, it's hard to say always but I have run this in loop 100 times and it reproduces the error consistently without the patch and after the patch it works consistently.
Fixes #1449
=> Add mutex on LinkFromPool to fix #1449

AUTHORS, deb/remote.go
I opened my IDE and a big yellow warning yelled at me:
=> remove useless nil check
