aptly-dev/aptly

- cmd/graph.go
https://github.com/smira/aptly/issues/241
modify：     cmd/graph.go
Signed-off-by: Zhang, Guodong <gdzhang@linx-info.com>
> aptly graph specific output filename

- http/download.go
see http://stackoverflow.com/a/19006050
> fix EOF during mirror update

- README.rst
> another example of aptly in Docker

- api/api.go
> Flush collection contents on each DB unlock in API.

- api/publish.go
- cmd/publish_snapshot.go
- deb/publish.go
- man/aptly.1
- man/aptly.1.ronn.tmpl
- system/t02_config/ConfigShowTest_gold
- system/t02_config/CreateConfigTest_gold
- system/t12_api/publish.py
- utils/config.go
- utils/config_test.go
Also add global configuration to disable 'skipContents' by
default.
> Make 'skipContents' configurable in API. #345

- deb/list.go
- deb/package_collection.go
- system/t11_package/ShowPackage7Test/pyspi_0.6.1-1.3.conflict.dsc
- system/t11_package/ShowPackage7Test_gold
- system/t11_package/show.py
Implement package list with duplicate entries, use it when
initiating search from PackageCollection.
> Fix package search missing duplicate packages. #225

- README.rst
Hi there,
We released our Aptly Puppet module some time ago and we recently pushed some updates. We thought it could be nice to have it in the official Aptly README :)
More information here : https://forge.puppet.com/TubeMogul/aptly
Thanks !
> Add TubeMogul Puppet module to README.rst

- .gitignore
- .goxc.json
- .travis.yml
- Makefile
- README.rst
- utils/compress_test.go
> Fix up build for recent versions of Go

- deb/publish.go
Fixes #476 
Sort filenames when building list of generated files for `Release`/`InRelease`.
> Sort paths when generating checksums for `Release`/`InRelease`

- Makefile
- man/Makefile
- man/aptly.1
This also updates man page with latest changes
> Add `make` automation to re-generate man page [ci skip]

- deb/changes.go
- deb/changes_test.go
fixes #331
package should pass name query and same source query
> include dbgsym packages

- .github/PULL_REQUEST_TEMPLATE.md
> Add bash completion to PR template [ci skip]

- .travis.yml
- system/t04_mirror/create.py
> Add Travis CI build on Go 1.8

- cmd/graph.go
Fixes #500
Pick viewer for graph file based on runtime platform.
Based on ideas from https://github.com/google/pprof/blob/master/internal/driver/commands.go#L337
> Customize viewer per platform

- Makefile
- README.rst
- bash_completion.d/aptly
Fixes #530
Original repository: https://github.com/aptly-dev/aptly-bash-completion
> Move bash completion to main aptly repo

- deb/snapshot.go
- deb/snapshot_test.go
- system/t05_snapshot/CreateSnapshot9Test_gold
- system/t05_snapshot/create.py
- system/t12_api/publish.py
- system/t12_api/snapshots.py
Fixes #288
This requirement was never really important, so it's easier to remove it.
> Allow snapshot to be created from empty local repo

- cmd/package_show.go
- context/context.go
- deb/changes.go
- deb/deb.go
- deb/package.go
- deb/package_test.go
- deb/publish.go
- deb/publish_test.go
- deb/query.go
- deb/reflist.go
- deb/remote.go
- linter.json
- query/syntax_test.go
- s3/public.go
- s3/server_test.go
- utils/gpg.go
> Enable `gosimple` and `ineffasign` linters

- linter.json
Ref: #528
Build is failing frequently in Travis CI due to deadline being exceeded
> Extend linters deadline

- Makefile
- console/progress.go
- deb/list.go
- deb/local_test.go
- deb/package.go
- deb/publish.go
- deb/publish_test.go
- deb/remote.go
- deb/remote_test.go
- deb/snapshot_test.go
- http/compression_test.go
- http/temp_test.go
- linter.json
- s3/public.go
- utils/config.go
Ref: #528
Enables "staticcheck", "varcheck", "structcheck", "aligncheck"
> More Go linters enabled, issues fixed

- bash_completion.d/aptly
> Add mirror edit option to bash auto-complete

- api/publish.go
- cmd/api_serve.go
- cmd/db_cleanup.go
- cmd/package_show.go
- cmd/publish_list.go
- cmd/publish_show.go
- cmd/repo_add.go
- cmd/repo_include.go
- cmd/repo_list.go
- cmd/serve.go
- cmd/snapshot_search.go
- cmd/snapshot_show.go
- cmd/task_run.go
- deb/changes.go
- deb/graph.go
- deb/publish.go
- files/public.go
- linter.json
> Enable `vetshadow` linter

- CONTRIBUTING.md
- README.rst
> Docs on contributing to aptly [ci skip]

- bash_completion.d/aptly
- man/aptly.1
- man/aptly.1.ronn.tmpl
- system/t06_publish/S3Publish3Test_gold
- system/t06_publish/S3Publish3Test_release
- system/t06_publish/SwiftPublish3Test_gold
- system/t06_publish/SwiftPublish3Test_release
Fix system tests, add -db-open-attempts to bash completion, small nits
for man page.
> Small fixups for upcoming 1.1.0 release

- deb/package_collection.go
- system/t11_package/ShowPackage8Test/pyspi_0.6.1-1.3.conflict.dsc
- system/t11_package/ShowPackage8Test_gold
- system/t11_package/show.py
> Allow package queries to return duplicate entries on `PackageCollection`

- Gopkg.lock
- vendor/github.com/syndtr/goleveldb/README.md
- vendor/github.com/syndtr/goleveldb/leveldb/db.go
- vendor/github.com/syndtr/goleveldb/leveldb/db_test.go
- vendor/github.com/syndtr/goleveldb/leveldb/doc.go
- vendor/github.com/syndtr/goleveldb/leveldb/iterator/iter.go
- vendor/github.com/syndtr/goleveldb/leveldb/memdb/memdb.go
- vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go
> Update goleveldb vendored dependency (see #662)

- README.rst
> Add link to aptly GUI

- .travis.yml
- Makefile
- aptly-api.service
- upload-artifacts.sh
This updates previous work in #739 to build
Debian packages and zip files for other OS.
> Move release build to Travis CI

- cmd/api_serve.go
- deb/remote.go
- deb/version_test.go
- http/download.go
- linter.json
- pgp/gnupg_test.go
- query/lex.go
- s3/server_test.go
- utils/utils.go
Fixes #806
Also updates linter config & fixes linting errors.
> Don't remove API file socket if it exists and usable

- .travis.yml
- system/t04_mirror/create.py
- upload-artifacts.sh
This should improve reliability of the release process.
Fixes broken nightly repos
> Fix upload artifacts script to fail, add release upload script

- system/t12_api/publish.py
> Add test for publishing with non-empty Origin & Label

- .github/workflows/ci.yml
- Makefile
- Fixes system env setup when something like pyenv is used.
- Fix default branch name in CI
> Fix master build and system test setup

- deb/publish.go
> fix: typo in the comments

- go.mod
- go.sum
Update module go-xz to the latest version.
There are significant performance optimizations in the commit https://github.com/smira/go-xz/commit/c2a07d4bedda1bbd14bc7b2176c083f4508511fc (mainly -T0 param.).
It also should also address this issue: https://github.com/aptly-dev/aptly/issues/825.
> upgrade go-xz go module

- system/api_lib.py
- system/t12_api/mirrors.py
- system/t12_api/packages.py
- system/t12_api/publish.py
- system/t12_api/repos.py
- system/t12_api/snapshots.py
- system/t12_api/tasks.py
Fixes #1158
Replaced 2 with TASK_SUCCEEDED, 3 with TASK_FAILED.
--> To make the Tests more readable
> Improvement: Remove Magic Numbers in Tests with Tasks

- .github/workflows/ci.yml
- Makefile
- api/files.go
- api/metrics.go
- api/repos.go
- api/router.go
- deb/publish.go
- system/api_lib.py
- system/lib.py
- system/t02_config/ConfigShowTest_gold
- system/t02_config/CreateConfigTest_gold
- system/t12_api/metrics.py
- system/t12_api/publish.py
- utils/config.go
- utils/config_test.go
- utils/logging.go
Duplicate of #1116 but with system tests.
Fixes #1017, maybe also fixes #975 but not sure about that
Related documentation change: https://github.com/aptly-dev/www.aptly.info/pull/103
> Api and files

- api/task.go
Fixes #
unnecessary use of fmt.Sprintf
> chore: unnecessary use of fmt.Sprintf

- go.mod
- go.sum
> Use tagged version of ProtonMail/go-crypto in go.mod

- http/download.go
Fixes #1250 
I believe this was introduced in https://github.com/aptly-dev/aptly/commit/25d7d7c037566c23485ab1b2446ca5d67d1777ca when the flowrate writer was removed from the io.MultiWriter. The flowrate writer is shared among download threads and blocks when downLimit is exceeded. It is not clear why this was removed in the above commit, since I believe the only point of the commit was to avoid a nil panic. 
Nonetheless, during my brief testing this seems to work now. I don't think I've reintroduced the panic bug from the original commit (should just write to io.Discard if progress == nil) but a second set of eyes would be good
> fix throttled downloader

- http/download.go
> Avoid nil panic when downloadSpeedLimit is set in api mode

- cmd/api_serve.go
- context/context.go
- http/download.go
> COVERAGE Make HTTP server wait for tasks before shutdown

- Releasing.md
- debian/changelog
Fixes #1457
Release 1.6.2 preparation
> Release 1.6.2

- AUTHORS
- Makefile
- api/mirror.go
- system/t12_api/mirrors.py
Fixes #1463 
I removed from the struct the parameters which are not part of [aptly mirror update](https://www.aptly.info/doc/aptly/mirror/update/)
> Fix non related API params from mirror update
